# Generated by Django 5.2.5 on 2025-09-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('car_colour', models.CharField(max_length=20)),
                ('car_name', models.CharField(max_length=20)),
                ('car_number', models.IntegerField(primary_key=True, serialize=False)),
                ('car_price', models.IntegerField()),
            ],
        ),
    ]
